export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="ulyssesys"
#ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
#CASE_SENSITIVE="true"
HYPHEN_INSENSITIVE="true"
#DISABLE_AUTO_UPDATE="true"
#DISABLE_UPDATE_PROMPT="true"
#export UPDATE_ZSH_DAYS=13
# Uncomment the following line if pasting URLs and other text is messed up.
#DISABLE_MAGIC_FUNCTIONS=true
#DISABLE_LS_COLORS="true"
# Uncomment the following line to disable auto-setting terminal title.
#DISABLE_AUTO_TITLE="true"
#ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
#DISABLE_UNTRACKED_FILES_DIRTY="true"
#HIST_STAMPS="mm/dd/yyyy"
#ZSH_CUSTOM=/path/to/new-custom-folder
plugins=(git zsh-syntax-highlighting dotenv nix-shell)

source $ZSH/oh-my-zsh.sh

#export MANPATH="/usr/local/man:$MANPATH"
#export LANG=en_US.UTF-8
export EDITOR=vim
#export ARCHFLAGS="-arch x86_64"

#alias zshconfig="mate ~/.zshrc"
#alias ohmyzsh="mate ~/.oh-my-zsh"

# Added by the user
#. ~/.local/share/rtx/plugins/go/set-env.zsh
export PATH=$PATH:$HOME/.cabal/bin:$HOME/.local/bin:$HOME/scripts

if command -v mise &> /dev/null; then; alias rtx=mise; fi
if command -v colormake &> /dev/null; then; alias make=colormake; fi
if command -v doas &> /dev/null; then; alias sudo=doas; fi

if command -v codium &> /dev/null && ! command -v code &> /dev/null; then
	alias code=codium
elif command -v code &> /dev/null && ! command -v codium &> /dev/null; then
	alias codium=code
fi

if command -v rtx &> /dev/null; then; eval "$(rtx activate zsh)"; fi
if command -v thefuck &> /dev/null; then; eval "$(thefuck --alias)"; fi
if command -v ng &> /dev/null; then; eval "$(ng completion script)"; fi
if command -v atuin &> /dev/null; then; eval "$(atuin init zsh)"; fi
if command -v zoxide &> /dev/null; then
	eval "$(zoxide init zsh --cmd cd)"
	export _ZO_EXCLUDE_DIRS=$_ZO_EXCLUDE_DIRS:/nix
fi

if [ -f "$HOME/.ghcup/env" ]; then; source "$HOME/.ghcup/env"; fi

autoload -Uz compinit && compinit

if [ -f "$HOME/.zshrc.local" ]; then; source "$HOME/.zshrc.local"; fi
